module.exports = {
  purge: {
    // enabled: process.env.NODE_ENV === "production" ? true : false,
    enabled: true,
    content: ["./layouts/**/*.html", "./content/**/*.md", "./content/**/*.html", "./src/**/*.js"],
    options: {
      // safelist classes generated by plugins like the datepicker
      safelist: [
        'w-64',
        'w-1/2',
        'rounded-l-lg',
        'rounded-r-lg',
        'bg-gray-200',
        'grid-cols-4',
        'grid-cols-7',
        'h-6',
        'leading-6',
        'h-9',
        'leading-9',
        'shadow-lg'
      ],
    }
  },
  darkMode: false, // or 'media' or 'class',
  plugins: [
    require('./plugin')
  ]
}
